project_id = "tfximqohiizipawvzkms"

[functions.generate-affirmation-image]
verify_jwt = false

[functions.generate-preview-image]
verify_jwt = false

[functions.generate-product-images]
verify_jwt = false

[functions.generate-affirmation-product-images]
verify_jwt = false

[functions.generate-affirmation-digital]
verify_jwt = false

[functions.handle-newsletter-signup]
verify_jwt = false
